use sprout_template_protocol::{ApplyRequest, Generator, ServiceKind, ServiceOutput};
use sprout_template_runtime::{Mutation, RuntimeError};

const ID: &str = "umami";
const REPOSITORY: &str = "https://github.com/umami-software/umami";
const COMMIT: &str = "ca661c7057984aa98ed4f7083d84dae2f65bfcb0";

const BUILD_MIGRATION: &str = include_str!("../assets/build-migration.mjs");
const MIGRATION_HANDLER: &str = include_str!("../assets/migration/index.mjs");
const MIGRATION_CONTROL: &str = include_str!("../assets/migration/control.json");
const MIGRATION_PACKAGE: &str = include_str!("../assets/migration/package.build.json");
const MIGRATION_SHRINKWRAP: &[u8] = include_bytes!("../assets/migration/npm-shrinkwrap.json");
const DEPLOY_WORKFLOW: &str = include_str!("../assets/sproutos-deploy.yml");

pub fn recipe(request: &ApplyRequest) -> Result<Vec<Mutation>, RuntimeError> {
    validate_request(request)?;
    Ok(vec![
        Mutation::own(".config/sproutos.toml", configuration(request)),
        Mutation::own("sproutos/build-migration.mjs", BUILD_MIGRATION),
        Mutation::own("sproutos/migration/control.json", MIGRATION_CONTROL),
        Mutation::own("sproutos/migration/index.mjs", MIGRATION_HANDLER),
        Mutation::own(
            "sproutos/migration/npm-shrinkwrap.json",
            MIGRATION_SHRINKWRAP,
        ),
        Mutation::own("sproutos/migration/package.build.json", MIGRATION_PACKAGE),
        Mutation::own(".github/workflows/sproutos-deploy.yml", DEPLOY_WORKFLOW),
    ])
}

fn validate_request(request: &ApplyRequest) -> Result<(), RuntimeError> {
    let template = &request.template;
    if template.id != ID
        || template.upstream_repository.trim_end_matches(".git") != REPOSITORY
        || template.upstream_commit != COMMIT
    {
        return Err(RuntimeError::UnsupportedUpstream(format!(
            "Umami recipe requires {REPOSITORY}@{COMMIT}"
        )));
    }
    if request.deployment.preset != "next"
        || request.deployment.capabilities != ["controlled_migrations", "next_standalone"]
    {
        return Err(RuntimeError::InvalidRequest(
            "Umami requires the next preset with controlled_migrations and next_standalone capabilities".into(),
        ));
    }
    if !request.user_inputs.is_empty() {
        return Err(RuntimeError::InvalidRequest(
            "Umami v1 recipe has no user inputs".into(),
        ));
    }
    if request.services.len() != 1 {
        return Err(RuntimeError::InvalidRequest(
            "Umami requires exactly one managed Postgres service".into(),
        ));
    }
    let postgres = &request.services[0];
    if postgres.key != "postgres"
        || postgres.kind != ServiceKind::Postgres
        || postgres.bindings.len() != 1
        || postgres.bindings[0].environment != "DATABASE_URL"
        || postgres.bindings[0].output != ServiceOutput::ConnectionUrl
    {
        return Err(RuntimeError::InvalidRequest(
            "Umami Postgres must bind connection_url to DATABASE_URL".into(),
        ));
    }
    if request.generated_inputs.len() != 1 {
        return Err(RuntimeError::InvalidRequest(
            "Umami requires the generated APP_SECRET input".into(),
        ));
    }
    let secret = &request.generated_inputs[0];
    if secret.key != "app_secret"
        || secret.environment != "APP_SECRET"
        || secret.generator != Generator::RandomBase64url
        || secret.bytes != 32
    {
        return Err(RuntimeError::InvalidRequest(
            "Umami APP_SECRET must be 32 random_base64url bytes".into(),
        ));
    }
    Ok(())
}

fn configuration(request: &ApplyRequest) -> String {
    let capabilities = request
        .deployment
        .capabilities
        .iter()
        .map(|value| format!("\"{value}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        r#"# Generated by the signed SproutOS Umami deployment template. No secret values belong here.
schema_version = 1

[template]
id = "umami"
catalogue_digest = "{}"
manifest_digest = "{}"
plugin_digest = "{}"
upstream_repository = "{}"
upstream_commit = "{}"

[deployment]
preset = "next"
runtime = "nodejs22.x"
capabilities = [{}]
build_command = "env -u VERCEL DATABASE_URL=postgresql://build:build@127.0.0.1:5432/build DISABLE_TELEMETRY=1 pnpm run build-docker && node sproutos/build-migration.mjs"
directory = ".next/standalone"
health_path = "/api/heartbeat"

[deployment.migration]
directory = ".sproutos/build/migration"
handler = "index.handler"
runtime = "nodejs22.x"

[[services]]
key = "postgres"
kind = "postgres"

[[services.bindings]]
environment = "DATABASE_URL"
output = "connection_url"

[[generated_inputs]]
key = "app_secret"
environment = "APP_SECRET"
generator = "random_base64url"
bytes = 32
"#,
        request.template.catalogue_digest,
        request.template.manifest_digest,
        request.template.plugin_digest,
        REPOSITORY,
        COMMIT,
        capabilities,
    )
}

#[cfg(test)]
mod tests {
    use std::fs;

    use sprout_template_protocol::{
        ApplyRequest, Deployment, EnvironmentBinding, GeneratedInput, ManagedService,
        TemplateIdentity,
    };
    use sprout_template_runtime::apply;
    use tempfile::tempdir;

    use super::*;

    fn request(workspace: &str) -> ApplyRequest {
        ApplyRequest {
            protocol_version: 1,
            workspace: workspace.into(),
            template: TemplateIdentity {
                id: ID.into(),
                catalogue_digest: format!("sha256:{}", "1".repeat(64)),
                manifest_digest: format!("sha256:{}", "2".repeat(64)),
                plugin_digest: format!("sha256:{}", "3".repeat(64)),
                upstream_repository: REPOSITORY.into(),
                upstream_commit: COMMIT.into(),
            },
            deployment: Deployment {
                preset: "next".into(),
                capabilities: vec!["controlled_migrations".into(), "next_standalone".into()],
            },
            services: vec![ManagedService {
                key: "postgres".into(),
                kind: ServiceKind::Postgres,
                bindings: vec![EnvironmentBinding {
                    environment: "DATABASE_URL".into(),
                    output: ServiceOutput::ConnectionUrl,
                }],
            }],
            user_inputs: vec![],
            generated_inputs: vec![GeneratedInput {
                key: "app_secret".into(),
                generator: Generator::RandomBase64url,
                bytes: 32,
                environment: "APP_SECRET".into(),
            }],
        }
    }

    #[test]
    fn golden_apply_is_exact_and_second_apply_is_empty() {
        let workspace = tempdir().unwrap();
        let request = request(workspace.path().to_str().unwrap());
        let first = apply(&request, recipe).unwrap();
        assert_eq!(first.len(), 7);
        assert_eq!(
            fs::read_to_string(workspace.path().join("sproutos/migration/index.mjs")).unwrap(),
            MIGRATION_HANDLER
        );
        assert_eq!(
            fs::read(
                workspace
                    .path()
                    .join("sproutos/migration/npm-shrinkwrap.json")
            )
            .unwrap(),
            MIGRATION_SHRINKWRAP
        );
        assert_eq!(
            fs::read_to_string(
                workspace
                    .path()
                    .join("sproutos/migration/package.build.json")
            )
            .unwrap(),
            MIGRATION_PACKAGE
        );
        assert!(
            !workspace
                .path()
                .join("sproutos/migration/package.json")
                .exists()
        );
        let config = fs::read_to_string(workspace.path().join(".config/sproutos.toml")).unwrap();
        assert!(config.contains("build-docker"));
        assert!(config.contains("directory = \".sproutos/build/migration\""));
        assert!(!config.contains("APP_SECRET ="));
        let workflow = fs::read_to_string(
            workspace
                .path()
                .join(".github/workflows/sproutos-deploy.yml"),
        )
        .unwrap();
        assert_eq!(workflow, DEPLOY_WORKFLOW);
        assert!(workflow.contains("on:\n  push:\n  workflow_dispatch:"));
        assert!(workflow.contains(
            "if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)"
        ));
        assert!(workflow.contains("permissions:\n      contents: read\n      id-token: write"));
        assert!(workflow.contains("migration-directory: .sproutos/build/migration"));
        assert!(workflow.contains("migration-handler: index.handler"));
        assert_eq!(workflow.matches("contents: read").count(), 2);
        assert_eq!(workflow.matches("id-token: write").count(), 1);
        assert!(workflow.contains("artifact-ids: ${{ needs.build.outputs.artifact-id }}"));
        assert!(workflow.contains("tar -xzf .sproutos/handoff/umami-deploy.tar.gz"));
        assert!(
            workflow.contains("set -- .next/standalone .next/static .sproutos/build/migration")
        );
        assert!(!workflow.contains("secrets."));
        assert!(!workflow.contains("SPROUTOS_TOKEN"));
        assert!(!workflow.contains("\n          token:"));
        assert!(!workflow.contains("\n          project:"));
        assert!(!workflow.contains("/v1/"));
        let action_commit = workflow
            .lines()
            .find_map(|line| {
                line.trim()
                    .strip_prefix("uses: MySproutOS/sproutos-deploy-action@")
            })
            .unwrap();
        assert_eq!(action_commit.len(), 40);
        assert!(action_commit.bytes().all(|byte| byte.is_ascii_hexdigit()));
        assert_ne!(action_commit, "0000000000000000000000000000000000000000");
        assert!(apply(&request, recipe).unwrap().is_empty());
    }

    #[test]
    fn refuses_wrong_commit_before_writing() {
        let workspace = tempdir().unwrap();
        let mut request = request(workspace.path().to_str().unwrap());
        request.template.upstream_commit = "0".repeat(40);
        assert!(matches!(
            apply(&request, recipe),
            Err(RuntimeError::UnsupportedUpstream(_))
        ));
        assert!(fs::read_dir(workspace.path()).unwrap().next().is_none());
    }

    #[test]
    fn refuses_conflicting_recipe_owned_file() {
        let workspace = tempdir().unwrap();
        let request = request(workspace.path().to_str().unwrap());
        fs::create_dir(workspace.path().join(".config")).unwrap();
        fs::write(
            workspace.path().join(".config/sproutos.toml"),
            "customer edit\n",
        )
        .unwrap();
        assert!(matches!(
            apply(&request, recipe),
            Err(RuntimeError::ConflictingChange(_))
        ));
    }
}
